
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase'; // Assuming you might generate types later

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl) {
  throw new Error("Missing env.NEXT_PUBLIC_SUPABASE_URL");
}
if (!supabaseAnonKey) {
  throw new Error("Missing env.NEXT_PUBLIC_SUPABASE_ANON_KEY");
}

// If you have Database types generated by Supabase CLI, you can use them here.
// For now, we'll use a generic type.
export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);
